/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoxadrez;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author giuli
 */
public class FrmPromocao extends javax.swing.JFrame {

    /**
     * Creates new form FrmPromocao
     */
    public FrmPromocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPormo = new javax.swing.JPanel();
        cbxPecaPromo = new javax.swing.JComboBox<>();
        lblTexto = new javax.swing.JLabel();
        lblPromo = new javax.swing.JLabel();
        lblPeao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(340, 200));
        getContentPane().setLayout(null);

        pPormo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pPormoMouseEntered(evt);
            }
        });

        cbxPecaPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cavalo", "Torre", "Bispo", "Dama" }));

        lblTexto.setText("Peça para a promoção:");

        lblPeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/pecasXadrez/imagens/peaoBranco.png"))); // NOI18N

        javax.swing.GroupLayout pPormoLayout = new javax.swing.GroupLayout(pPormo);
        pPormo.setLayout(pPormoLayout);
        pPormoLayout.setHorizontalGroup(
            pPormoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPormoLayout.createSequentialGroup()
                .addGroup(pPormoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPormoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPormoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblPeao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pPormoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPecaPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pPormoLayout.setVerticalGroup(
            pPormoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPormoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pPormoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto)
                    .addComponent(cbxPecaPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPormoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(pPormo);
        pPormo.setBounds(0, 0, 340, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pPormoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPormoMouseEntered
        String promocao = cbxPecaPromo.getSelectedItem().toString();
        switch (promocao) {
            case "Cavalo":
                lblPromo.setIcon(new ImageIcon("C:\\Users\\giuli\\Eu\\facul\\git\\Xadrez\\ProjetoXadrez\\src\\jogo\\pecasXadrez\\imagens\\cavaloBranco.png"));
                break;
            case "Torre":
                lblPromo.setIcon(new ImageIcon("C:\\Users\\giuli\\Eu\\facul\\git\\Xadrez\\ProjetoXadrez\\src\\jogo\\pecasXadrez\\imagens\\torreBranca.png"));
                break;
            case "Bispo":
                lblPromo.setIcon(new ImageIcon("C:\\Users\\giuli\\Eu\\facul\\git\\Xadrez\\ProjetoXadrez\\src\\jogo\\pecasXadrez\\imagens\\bispoBranco.png"));
                break;
            case "Dama":
                lblPromo.setIcon(new ImageIcon("C:\\Users\\giuli\\Eu\\facul\\git\\Xadrez\\ProjetoXadrez\\src\\jogo\\pecasXadrez\\imagens\\rainhaBranca.png"));
                break;

            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_pPormoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPromocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxPecaPromo;
    private javax.swing.JLabel lblPeao;
    private javax.swing.JLabel lblPromo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel pPormo;
    // End of variables declaration//GEN-END:variables
}
